<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();

        foreach ($categories as $category) {
            $products = $this->getProductsForCategory($category->slug);
            
            foreach ($products as $productData) {
                Product::updateOrCreate(
                    ['slug' => $productData['slug']],
                    array_merge($productData, [
                        'category_id' => $category->id,
                    ])
                );
            }
        }
    }

    /**
     * Get products data for a specific category.
     */
    private function getProductsForCategory(string $categorySlug): array
    {
        $products = [
            'living-room' => [
                [
                    'name' => 'Modern Sofa Set',
                    'slug' => 'modern-sofa-set',
                    'description' => '3-seater sofa with removable covers, perfect for any living room. Comfortable and stylish design.',
                    'price' => 599.99,
                    'sku' => 'LR-SOFA-001',
                    'stock_quantity' => 25,
                    'rating' => 4.8,
                    'reviews_count' => 1247,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'Coffee Table with Storage',
                    'slug' => 'coffee-table-storage',
                    'description' => 'Modern coffee table with hidden storage compartment. Perfect for keeping your living room organized.',
                    'price' => 249.99,
                    'sku' => 'LR-TABLE-002',
                    'stock_quantity' => 18,
                    'rating' => 4.6,
                    'reviews_count' => 892,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 2,
                ],
                [
                    'name' => 'TV Stand Entertainment Center',
                    'slug' => 'tv-stand-entertainment-center',
                    'description' => 'Sleek TV stand with cable management and ample storage for media devices.',
                    'price' => 349.99,
                    'sku' => 'LR-TV-003',
                    'stock_quantity' => 32,
                    'rating' => 4.7,
                    'reviews_count' => 634,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 3,
                ],
                [
                    'name' => 'Accent Chair',
                    'slug' => 'accent-chair',
                    'description' => 'Comfortable accent chair with modern design. Perfect for reading or relaxing.',
                    'price' => 199.99,
                    'sku' => 'LR-CHAIR-004',
                    'stock_quantity' => 15,
                    'rating' => 4.5,
                    'reviews_count' => 456,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 4,
                ],
                [
                    'name' => 'Bookshelf Display Unit',
                    'slug' => 'bookshelf-display-unit',
                    'description' => '5-tier bookshelf perfect for displaying books, decor, and collectibles.',
                    'price' => 179.99,
                    'sku' => 'LR-SHELF-005',
                    'stock_quantity' => 22,
                    'rating' => 4.4,
                    'reviews_count' => 789,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 5,
                ],
                [
                    'name' => 'Sectional Sofa',
                    'slug' => 'sectional-sofa',
                    'description' => 'Large L-shaped sectional sofa with chaise. Seats up to 5 people comfortably.',
                    'price' => 899.99,
                    'sku' => 'LR-SOFA-006',
                    'stock_quantity' => 12,
                    'rating' => 4.9,
                    'reviews_count' => 523,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 6,
                ],
                [
                    'name' => 'Side Table Set',
                    'slug' => 'side-table-set',
                    'description' => 'Set of 2 matching side tables with drawer storage. Modern and functional.',
                    'price' => 149.99,
                    'sku' => 'LR-TABLE-007',
                    'stock_quantity' => 28,
                    'rating' => 4.3,
                    'reviews_count' => 312,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 7,
                ],
                [
                    'name' => 'Floor Lamp',
                    'slug' => 'floor-lamp',
                    'description' => 'Modern floor lamp with adjustable height and dimmable LED light.',
                    'price' => 89.99,
                    'sku' => 'LR-LAMP-008',
                    'stock_quantity' => 45,
                    'rating' => 4.6,
                    'reviews_count' => 678,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 8,
                ],
                [
                    'name' => 'Ottoman Storage Bench',
                    'slug' => 'ottoman-storage-bench',
                    'description' => 'Versatile ottoman that doubles as storage. Perfect for extra seating and organization.',
                    'price' => 129.99,
                    'sku' => 'LR-OTTO-009',
                    'stock_quantity' => 20,
                    'rating' => 4.5,
                    'reviews_count' => 401,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 9,
                ],
                [
                    'name' => 'Wall-Mounted Shelves',
                    'slug' => 'wall-mounted-shelves',
                    'description' => 'Set of 3 floating shelves for wall mounting. Easy installation and modern look.',
                    'price' => 79.99,
                    'sku' => 'LR-SHELF-010',
                    'stock_quantity' => 38,
                    'rating' => 4.4,
                    'reviews_count' => 567,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 10,
                ],
            ],
            'bedroom' => [
                [
                    'name' => 'Platform Bed Frame',
                    'slug' => 'platform-bed-frame',
                    'description' => 'Queen size bed with storage drawers, modern design. No box spring needed.',
                    'price' => 399.99,
                    'sku' => 'BR-BED-001',
                    'stock_quantity' => 30,
                    'rating' => 4.6,
                    'reviews_count' => 634,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'Dresser with Mirror',
                    'slug' => 'dresser-with-mirror',
                    'description' => '6-drawer dresser with attached mirror. Ample storage for clothing and accessories.',
                    'price' => 449.99,
                    'sku' => 'BR-DRESS-002',
                    'stock_quantity' => 18,
                    'rating' => 4.7,
                    'reviews_count' => 456,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 2,
                ],
                [
                    'name' => 'Nightstand Set',
                    'slug' => 'nightstand-set',
                    'description' => 'Set of 2 matching nightstands with drawer and shelf. Perfect bedside storage.',
                    'price' => 179.99,
                    'sku' => 'BR-NIGHT-003',
                    'stock_quantity' => 25,
                    'rating' => 4.5,
                    'reviews_count' => 523,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 3,
                ],
                [
                    'name' => 'Wardrobe Closet',
                    'slug' => 'wardrobe-closet',
                    'description' => 'Freestanding wardrobe with hanging space and shelves. Great for small bedrooms.',
                    'price' => 299.99,
                    'sku' => 'BR-WARD-004',
                    'stock_quantity' => 15,
                    'rating' => 4.4,
                    'reviews_count' => 312,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 4,
                ],
                [
                    'name' => 'Mattress',
                    'slug' => 'mattress',
                    'description' => 'Memory foam mattress with cooling gel. Queen size, medium firmness.',
                    'price' => 599.99,
                    'sku' => 'BR-MATT-005',
                    'stock_quantity' => 22,
                    'rating' => 4.8,
                    'reviews_count' => 892,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 5,
                ],
                [
                    'name' => 'Vanity Table',
                    'slug' => 'vanity-table',
                    'description' => 'Elegant vanity table with mirror and stool. Perfect for getting ready.',
                    'price' => 249.99,
                    'sku' => 'BR-VAN-006',
                    'stock_quantity' => 12,
                    'rating' => 4.6,
                    'reviews_count' => 234,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 6,
                ],
                [
                    'name' => 'Under Bed Storage',
                    'slug' => 'under-bed-storage',
                    'description' => 'Set of 4 under-bed storage boxes. Maximize your bedroom storage space.',
                    'price' => 49.99,
                    'sku' => 'BR-STOR-007',
                    'stock_quantity' => 50,
                    'rating' => 4.3,
                    'reviews_count' => 678,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 7,
                ],
                [
                    'name' => 'Bedroom Bench',
                    'slug' => 'bedroom-bench',
                    'description' => 'Upholstered bench for the end of your bed. Extra seating and storage.',
                    'price' => 129.99,
                    'sku' => 'BR-BENCH-008',
                    'stock_quantity' => 20,
                    'rating' => 4.4,
                    'reviews_count' => 345,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 8,
                ],
                [
                    'name' => 'Jewelry Armoire',
                    'slug' => 'jewelry-armoire',
                    'description' => 'Compact jewelry armoire with multiple compartments and mirror.',
                    'price' => 99.99,
                    'sku' => 'BR-JEW-009',
                    'stock_quantity' => 28,
                    'rating' => 4.5,
                    'reviews_count' => 189,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 9,
                ],
                [
                    'name' => 'Bedroom Rug',
                    'slug' => 'bedroom-rug',
                    'description' => 'Soft plush rug for bedroom. Adds comfort and style to your space.',
                    'price' => 79.99,
                    'sku' => 'BR-RUG-010',
                    'stock_quantity' => 35,
                    'rating' => 4.6,
                    'reviews_count' => 567,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 10,
                ],
            ],
            'dining-room' => [
                [
                    'name' => 'Scandinavian Dining Table',
                    'slug' => 'scandinavian-dining-table',
                    'description' => 'Solid wood dining table seats 6, minimalist design. Perfect for family meals.',
                    'price' => 449.99,
                    'sku' => 'DR-TABLE-001',
                    'stock_quantity' => 20,
                    'rating' => 4.9,
                    'reviews_count' => 892,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'Dining Chair Set',
                    'slug' => 'dining-chair-set',
                    'description' => 'Set of 4 modern dining chairs with comfortable padding. Matches dining table.',
                    'price' => 199.99,
                    'sku' => 'DR-CHAIR-002',
                    'stock_quantity' => 30,
                    'rating' => 4.7,
                    'reviews_count' => 634,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 2,
                ],
                [
                    'name' => 'Buffet Sideboard',
                    'slug' => 'buffet-sideboard',
                    'description' => 'Elegant sideboard with drawers and cabinets. Perfect for storing dinnerware.',
                    'price' => 349.99,
                    'sku' => 'DR-BUFF-003',
                    'stock_quantity' => 15,
                    'rating' => 4.6,
                    'reviews_count' => 456,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 3,
                ],
                [
                    'name' => 'Bar Cart',
                    'slug' => 'bar-cart',
                    'description' => 'Mobile bar cart with shelves and wine storage. Perfect for entertaining.',
                    'price' => 179.99,
                    'sku' => 'DR-CART-004',
                    'stock_quantity' => 22,
                    'rating' => 4.5,
                    'reviews_count' => 312,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 4,
                ],
                [
                    'name' => 'Dining Room Chandelier',
                    'slug' => 'dining-room-chandelier',
                    'description' => 'Elegant chandelier with crystal accents. Creates beautiful ambient lighting.',
                    'price' => 299.99,
                    'sku' => 'DR-LIGHT-005',
                    'stock_quantity' => 18,
                    'rating' => 4.8,
                    'reviews_count' => 523,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 5,
                ],
                [
                    'name' => 'China Cabinet',
                    'slug' => 'china-cabinet',
                    'description' => 'Glass-front china cabinet with lighting. Showcase your fine dinnerware.',
                    'price' => 499.99,
                    'sku' => 'DR-CAB-006',
                    'stock_quantity' => 12,
                    'rating' => 4.7,
                    'reviews_count' => 234,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 6,
                ],
                [
                    'name' => 'Dining Bench',
                    'slug' => 'dining-bench',
                    'description' => 'Wooden dining bench seats 2-3 people. Space-saving alternative to chairs.',
                    'price' => 149.99,
                    'sku' => 'DR-BENCH-007',
                    'stock_quantity' => 25,
                    'rating' => 4.4,
                    'reviews_count' => 401,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 7,
                ],
                [
                    'name' => 'Wine Rack',
                    'slug' => 'wine-rack',
                    'description' => 'Wall-mounted wine rack holds 12 bottles. Perfect for wine enthusiasts.',
                    'price' => 69.99,
                    'sku' => 'DR-WINE-008',
                    'stock_quantity' => 40,
                    'rating' => 4.5,
                    'reviews_count' => 567,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 8,
                ],
                [
                    'name' => 'Table Runner Set',
                    'slug' => 'table-runner-set',
                    'description' => 'Set of 2 elegant table runners. Adds sophistication to your dining table.',
                    'price' => 39.99,
                    'sku' => 'DR-RUN-009',
                    'stock_quantity' => 60,
                    'rating' => 4.3,
                    'reviews_count' => 789,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 9,
                ],
                [
                    'name' => 'Placemat Set',
                    'slug' => 'placemat-set',
                    'description' => 'Set of 6 woven placemats with matching napkins. Protect your table in style.',
                    'price' => 29.99,
                    'sku' => 'DR-MAT-010',
                    'stock_quantity' => 80,
                    'rating' => 4.4,
                    'reviews_count' => 456,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 10,
                ],
            ],
            'kitchen' => [
                [
                    'name' => 'Kitchen Island',
                    'slug' => 'kitchen-island',
                    'description' => 'Rolling kitchen island with storage and butcher block top. Extra prep space.',
                    'price' => 399.99,
                    'sku' => 'KT-ISL-001',
                    'stock_quantity' => 15,
                    'rating' => 4.7,
                    'reviews_count' => 523,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'Pantry Cabinet',
                    'slug' => 'pantry-cabinet',
                    'description' => 'Tall pantry cabinet with adjustable shelves. Organize your kitchen storage.',
                    'price' => 299.99,
                    'sku' => 'KT-PANT-002',
                    'stock_quantity' => 20,
                    'rating' => 4.6,
                    'reviews_count' => 456,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 2,
                ],
                [
                    'name' => 'Kitchen Cart',
                    'slug' => 'kitchen-cart',
                    'description' => 'Mobile kitchen cart with shelves and towel bar. Versatile storage solution.',
                    'price' => 149.99,
                    'sku' => 'KT-CART-003',
                    'stock_quantity' => 28,
                    'rating' => 4.5,
                    'reviews_count' => 634,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 3,
                ],
                [
                    'name' => 'Pot Rack',
                    'slug' => 'pot-rack',
                    'description' => 'Ceiling-mounted pot rack. Keep your cookware organized and accessible.',
                    'price' => 89.99,
                    'sku' => 'KT-POT-004',
                    'stock_quantity' => 22,
                    'rating' => 4.4,
                    'reviews_count' => 312,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 4,
                ],
                [
                    'name' => 'Kitchen Storage Baskets',
                    'slug' => 'kitchen-storage-baskets',
                    'description' => 'Set of 3 woven storage baskets. Perfect for organizing pantry items.',
                    'price' => 49.99,
                    'sku' => 'KT-BASK-005',
                    'stock_quantity' => 45,
                    'rating' => 4.3,
                    'reviews_count' => 567,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 5,
                ],
                [
                    'name' => 'Spice Rack',
                    'slug' => 'spice-rack',
                    'description' => 'Wall-mounted spice rack holds 20 jars. Keep spices organized and visible.',
                    'price' => 39.99,
                    'sku' => 'KT-SPICE-006',
                    'stock_quantity' => 35,
                    'rating' => 4.5,
                    'reviews_count' => 401,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 6,
                ],
                [
                    'name' => 'Kitchen Stool Set',
                    'slug' => 'kitchen-stool-set',
                    'description' => 'Set of 2 bar stools with backrest. Perfect for kitchen island seating.',
                    'price' => 179.99,
                    'sku' => 'KT-STOOL-007',
                    'stock_quantity' => 25,
                    'rating' => 4.6,
                    'reviews_count' => 234,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 7,
                ],
                [
                    'name' => 'Cutting Board Set',
                    'slug' => 'cutting-board-set',
                    'description' => 'Set of 3 bamboo cutting boards in different sizes. Durable and eco-friendly.',
                    'price' => 59.99,
                    'sku' => 'KT-BOARD-008',
                    'stock_quantity' => 50,
                    'rating' => 4.7,
                    'reviews_count' => 678,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 8,
                ],
                [
                    'name' => 'Kitchen Towel Set',
                    'slug' => 'kitchen-towel-set',
                    'description' => 'Set of 6 absorbent kitchen towels. Soft and durable for daily use.',
                    'price' => 24.99,
                    'sku' => 'KT-TOWEL-009',
                    'stock_quantity' => 100,
                    'rating' => 4.4,
                    'reviews_count' => 892,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 9,
                ],
                [
                    'name' => 'Dish Drying Rack',
                    'slug' => 'dish-drying-rack',
                    'description' => 'Stainless steel dish drying rack with utensil holder. Keeps sink area organized.',
                    'price' => 34.99,
                    'sku' => 'KT-RACK-010',
                    'stock_quantity' => 60,
                    'rating' => 4.5,
                    'reviews_count' => 345,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 10,
                ],
            ],
            'office' => [
                [
                    'name' => 'Desk Chair',
                    'slug' => 'desk-chair',
                    'description' => 'Ergonomic office chair with lumbar support. Comfortable for long work sessions.',
                    'price' => 249.99,
                    'sku' => 'OF-CHAIR-001',
                    'stock_quantity' => 35,
                    'rating' => 4.8,
                    'reviews_count' => 1234,
                    'is_active' => true,
                    'is_featured' => true,
                    'sort_order' => 1,
                ],
                [
                    'name' => 'Writing Desk',
                    'slug' => 'writing-desk',
                    'description' => 'Modern writing desk with drawer. Perfect for home office or study.',
                    'price' => 199.99,
                    'sku' => 'OF-DESK-002',
                    'stock_quantity' => 28,
                    'rating' => 4.6,
                    'reviews_count' => 567,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 2,
                ],
                [
                    'name' => 'File Cabinet',
                    'slug' => 'file-cabinet',
                    'description' => '2-drawer file cabinet with lock. Organize important documents securely.',
                    'price' => 149.99,
                    'sku' => 'OF-FILE-003',
                    'stock_quantity' => 22,
                    'rating' => 4.5,
                    'reviews_count' => 456,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 3,
                ],
                [
                    'name' => 'Bookshelf',
                    'slug' => 'bookshelf',
                    'description' => '5-tier bookshelf for office or study. Display books and office supplies.',
                    'price' => 129.99,
                    'sku' => 'OF-SHELF-004',
                    'stock_quantity' => 30,
                    'rating' => 4.4,
                    'reviews_count' => 312,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 4,
                ],
                [
                    'name' => 'Monitor Stand',
                    'slug' => 'monitor-stand',
                    'description' => 'Adjustable monitor stand with storage. Elevate your workspace setup.',
                    'price' => 79.99,
                    'sku' => 'OF-STAND-005',
                    'stock_quantity' => 40,
                    'rating' => 4.6,
                    'reviews_count' => 523,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 5,
                ],
                [
                    'name' => 'Desk Organizer',
                    'slug' => 'desk-organizer',
                    'description' => 'Desktop organizer with compartments. Keep your desk tidy and organized.',
                    'price' => 39.99,
                    'sku' => 'OF-ORG-006',
                    'stock_quantity' => 55,
                    'rating' => 4.3,
                    'reviews_count' => 789,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 6,
                ],
                [
                    'name' => 'Office Lamp',
                    'slug' => 'office-lamp',
                    'description' => 'Adjustable desk lamp with LED light. Perfect task lighting for your workspace.',
                    'price' => 59.99,
                    'sku' => 'OF-LAMP-007',
                    'stock_quantity' => 45,
                    'rating' => 4.5,
                    'reviews_count' => 401,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 7,
                ],
                [
                    'name' => 'Cable Management Box',
                    'slug' => 'cable-management-box',
                    'description' => 'Cable organizer box hides and organizes all your cables. Clean workspace solution.',
                    'price' => 29.99,
                    'sku' => 'OF-CABLE-008',
                    'stock_quantity' => 65,
                    'rating' => 4.4,
                    'reviews_count' => 234,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 8,
                ],
                [
                    'name' => 'Desk Mat',
                    'slug' => 'desk-mat',
                    'description' => 'Large desk mat protects your desk and provides smooth mouse surface.',
                    'price' => 34.99,
                    'sku' => 'OF-MAT-009',
                    'stock_quantity' => 70,
                    'rating' => 4.5,
                    'reviews_count' => 567,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 9,
                ],
                [
                    'name' => 'Wall-Mounted Shelves',
                    'slug' => 'wall-mounted-shelves-office',
                    'description' => 'Set of 3 floating shelves for office. Display decor and keep items organized.',
                    'price' => 89.99,
                    'sku' => 'OF-SHELF-010',
                    'stock_quantity' => 38,
                    'rating' => 4.4,
                    'reviews_count' => 345,
                    'is_active' => true,
                    'is_featured' => false,
                    'sort_order' => 10,
                ],
            ],
        ];

        return $products[$categorySlug] ?? [];
    }
}
